### ISSUE TITLE
Upgrade source code to Java 8

### ISSUE THREAD

**Issue by lukaseder** [Chrriis/RRDiagram#11]
The source code makes use of quite a few `@FunctionalInterfaces`, which would be really nice to use with lambda syntax.

@Chrriis: Do you agree if the source and target language level is upgraded to 1.8?

**Comment by Chrriis** [comment]
@lukaseder I am not really against Java 8, in which case we could convert functional interfaces to lambda. I am not sure about using functional constructs like streams though (we could discuss a few cases if you wanted to do so).
That being said, such change would mostly be for cosmetic reasons but would prevent users stuck with old JDK to use the library. Sometimes, with database and servers, there are such users.
I let you judge :)

**Comment by lukaseder** [comment]
Hmm, we don't absolutely need it. OK, let's postpone that - you're right. There are still quite few people using Java 7 (and some Java 6 users, too)
