### ISSUE TITLE
broken link in readme

### ISSUE THREAD

**Issue by billy1380** [Chrriis/RRDiagram#16]
Should the link be http://www.bottlecaps.de/rr/ui
instead of
http://railroad.my28msec.com/rr/ui
or is the site just dead?

**Comment by Chrriis** [comment]
This other link does not seem to work either, but it is the latest I could find.
I noticed some sources are available that might be the original project: https://github.com/GuntherRademacher/rr
I did not put that in the readme because I don't know the history of those sources...
