### ISSUE TITLE
Wrong output?

### ISSUE THREAD

**Issue by Coldeagle27** [Chrriis/RRDiagram#18]
Given the following input:
`join_simple ::= relation "JOIN" relation`
the following diagram is created:
![join_simple1](https://user-images.githubusercontent.com/9353219/36353404-5738e07a-14c6-11e8-91a4-52eff16efa84.png)

However this input:
`join_simple ::= (relation) "JOIN" (relation)`
produces the following diagram:
![join_simple2](https://user-images.githubusercontent.com/9353219/36353407-5b5fadf0-14c6-11e8-8fc7-706acf7cb54f.png)

Shouldn't both specifications lead to the second diagram?

**Comment by Chrriis** [comment]
both of these worked for me:
```
join_simple1 ::= relation "JOIN" relation;
join_simple2 ::= (relation) "JOIN" (relation);
```

Note the semi-colon at the end.
