### ISSUE TITLE
Parsing error for what appears to be valid rule

### ISSUE THREAD

**Issue by JohnCokerC3** [Chrriis/RRDiagram#20]
This rule causes a parsing error:

```
func_mods ::= func_mod+ ('private' func_mod*)?
```

```
java.lang.IllegalStateException: Expecting start of a comment after '(' but could not find '*'!
	at net.nextencia.rrdiagram.grammar.model.BNFToGrammar.convert(BNFToGrammar.java:320)
	at net.nextencia.rrdiagram.grammar.model.BNFToGrammar.convert(BNFToGrammar.java:285)
```

It can be reproduced with this test:

```java
  @Test
  public void testRepeatedOptional() {
     svg("func_mod+ ('private' func_mod*)?");
  }
```

**Comment by Chrriis** [comment]
This was a silly error of the form:
`cond1 && cond2 && a ==null? b == null: a.equals(b)`
which should have been:
`cond1 && cond2 && (a ==null? b == null: a.equals(b))`

Thanks for reporting!

**Comment by Chrriis** [comment]
Just to mention that there was a bug which got fixed with that rule, but the original description of the problem did not match my observations with the latest code I used.
