### ISSUE TITLE
RRDiagram.jar can't be started

### ISSUE THREAD

**Issue by JoopN** [Chrriis/RRDiagram#21]
I get this in my bugs file;
Failed to load Main-Class manifest attribute from
RRDiagram.jar

I use this to run the program;
java -Duser.home=I:\PROGRAMS\RRDiagram -jar RRDiagram.jar 2>RRDiagram-bugs.txt

Of course java can be found. 

Question: How to start the program?

**Comment by Chrriis** [comment]
The JAR is not a runnable JAR. It is a library to add to your classpath and then you would use the API.
