### ISSUE TITLE
Change the License to ASL 2.0

### ISSUE THREAD

**Issue by lukaseder** [Chrriis/RRDiagram#5]
In order to facilitate both contributions and distribution, I suggest the license be changed to [ASL 2.0](https://www.apache.org/licenses/LICENSE-2.0). In particular the legal impact any modification may have on the distribution of the library is not very clear in the LGPL.

Besides, the ASL is understood not to require and CLA to make sure that all contributions are made under the terms of the ASL as well.

@Chrriis: Do you confirm this license change or do you prefer RRDiagram to stay under the terms of the LGPL?

**Comment by Chrriis** [comment]
@lukaseder I am fine with the suggested license change. I picked LGPL by habit, because in the olden days this was my favourite (much better than GPL for my audiences).

**Comment by lukaseder** [comment]
Perfect, thank you.

**Comment by Chrriis** [comment]
There are still some files referencing "LGPL". e.g.: RRDiagram/Release/readme.txt
