### ISSUE TITLE
Release this library on Maven Central

### ISSUE THREAD

**Issue by lukaseder** [Chrriis/RRDiagram#8]
Instructions here:
http://central.sonatype.org/pages/ossrh-guide.html

This change depends on https://github.com/Chrriis/RRDiagram/issues/15 (renaming of Maven groupId)

**Comment by Chrriis** [comment]
As far as I know this was fixed a long time ago:
https://central.sonatype.com/artifact/net.nextencia/rrdiagram
https://mvnrepository.com/artifact/net.nextencia/rrdiagram
